Src/EmployeeManagement.Web/Controllers/BenefitsController.cs
using AutoMapper;
using EmployeeManagement.Core.Model;
using EmployeeManagement.Core.Repositories;
using EmployeeManagement.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagement.Web.Controllers
{
    public class BenefitsController : Controller
    {
        private readonly IBenefitsRepository benefitsRepository;
        private readonly IMapper mapper;

        public BenefitsController(IBenefitsRepository benefitsRepository, IMapper mapper)
        {
            this.benefitsRepository = benefitsRepository;
            this.mapper = mapper;
        }

        // GET: Benefits
        public IActionResult Index()
        {
            return View((mapper.Map<BenefitPolicy, BenefitPolicyViewModel>(benefitsRepository.GetCompanyBenefitsInformation())));
        }

        // GET: Benefits/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var benefitPolicy = benefitsRepository.GetCompanyBenefitsInformation();
            if (benefitPolicy == null)
            {
                return NotFound();
            }

            return View(mapper.Map<BenefitPolicy, BenefitPolicyViewModel>(benefitPolicy));
        }

        // GET: Benefits/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var benefitPolicy = benefitsRepository.GetCompanyBenefitsInformation();
            if (benefitPolicy == null)
            {
                return NotFound();
            }
            return View(mapper.Map<BenefitPolicy, BenefitPolicyViewModel>(benefitPolicy));
        }

        // POST: Benefits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("ID,EmployeeCostPerYear,DependentCostPerYear,LetterToDiscount,DiscountAmount,IsActive,ChecksPerYear")] BenefitPolicyViewModel benefitPolicy)
        {
            if (id != benefitPolicy.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    benefitsRepository.UpdateCompanyBenefits(mapper.Map<BenefitPolicyViewModel, BenefitPolicy>(benefitPolicy));
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(benefitPolicy);
        }
    }
}

Src/EmployeeManagement.Web/Controllers/EmployeesController.cs
using AutoMapper;
using EmployeeManagement.Core;
using EmployeeManagement.Core.Model;
using EmployeeManagement.Core.Repositories;
using EmployeeManagement.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace EmployeeManagement.Web.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IEmployeeRepository employeeRepository;
        private readonly IMapper mapper;

        public EmployeesController(IEmployeeRepository employeeRepository, IMapper mapper)
        {
            this.employeeRepository = employeeRepository;
            this.mapper = mapper;
        }

        // GET: Employees
        public IActionResult Index()
        {
            return View((mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employeeRepository.GetEmployees())));
        }

        //GET: Employees/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = employeeRepository.GetEmployeeByID(id.Value);
            if (employee == null)
            {
                return NotFound();
            }

            return View(mapper.Map<Employee, EmployeeViewModel>(employee));
        }

        //[Bind("EmployeeVM,Relationship,CurrentDependents,LastName,FirstName")]
        public IActionResult Dependents(DependentViewModel vm)
        {
            return View(vm);
        }

        [HttpPost]
        public IActionResult AddDependents([Bind("EmployeeVM,EmployeeID,LastName,FirstName,Relationship,Dependents")] DependentViewModel dependentViewModel)
        {
            if (ModelState.IsValid)
            {
                var employee = employeeRepository.GetEmployeeByID(dependentViewModel.EmployeeID);
                if (employee == null)
                {
                    return NotFound();
                }

                var dependent = mapper.Map<DependentViewModel, Dependent>(dependentViewModel);
                var listOfDependents = employee.Dependents == null ? new List<Dependent>() : employee.Dependents.ToList();
                listOfDependents.Add(dependent);
                employee.Dependents = listOfDependents;
                employeeRepository.AddEntity(dependent);
                dependentViewModel.CurrentDependents =
                    mapper.Map<List<Dependent>, List<DependentViewModel>>(listOfDependents);

                return View(nameof(Dependents), dependentViewModel);
            }
            return View(nameof(Dependents), dependentViewModel);
        }

        public IActionResult PreviewCosts(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employeeCosts = employeeRepository.GetEmployeeCost(id.Value);
            if (employeeCosts == null)
            {
                return NotFound();
            }
            return View(employeeCosts);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Salary,ID,LastName,FirstName,Email,Dependents")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employeeRepository.AddEntity(employee);
                var vm = new DependentViewModel { EmployeeID = employee.ID };
                return View(nameof(Dependents), vm);
            }
            return View(mapper.Map<Employee, EmployeeViewModel>(employee));
        }

        // GET: Employees/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = employeeRepository.GetEmployeeByID(id.Value);
            if (employee == null)
            {
                return NotFound();
            }
            return View(mapper.Map<Employee, EmployeeViewModel>(employee));
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Salary,ID,LastName,FirstName,Email,Dependents")] Employee employee)
        {
            if (id != employee.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    employeeRepository.UpdateEmployee(employee);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mapper.Map<Employee, EmployeeViewModel>(employee));
        }

        // GET: Employees/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = employeeRepository.GetEmployeeByID(id.Value);
            if (employee == null)
            {
                return NotFound();
            }

            return View(mapper.Map<Employee, EmployeeViewModel>(employee));
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            employeeRepository.DeleteEmployee(id);
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return employeeRepository.EmployeeExists(id);
        }
    }
}

Src/EmployeeManagement.Web/Controllers/ManagementController.cs
using EmployeeManagement.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.Web.Controllers
{
    public class ManagementController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("Contact")]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost("Contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Send the email
                //_mailService.SendMessage(model.Email, model.Subject, model.Message);
                ViewBag.UserMessage = "Mail Sent!";
                ModelState.Clear();
            }

            return View();
        }

        [HttpGet("About")]
        public IActionResult About()
        {
            return View();
        }
    }
}

Src/EmployeeManagement.Web/Views/Shared/_EmployeeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Employee Management: @ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
            <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="theMenu" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Management" asp-action="Index"><i class="fas fa-hand-holding-usd"></i>Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Employees" asp-action="Create">Add Employee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Employees" asp-action="Index">View Employees</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <section class="container">
        <div class="col-md-12">
            <h2 class="text-center">@ViewBag.Title</h2>
            @RenderBody()
        </div>
    </section>
    <footer class="container">
        <div class="text-center">Copyright 2020 Marvelo LLC</div>
    </footer>

    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/js/index.js"></script>*@
    @RenderSection("scripts", false)
</body>
</html>

Src/EmployeeManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Employee Management: @ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
            <i class="fas fa-hand-holding-usd"></i>
            <button type="button" class="btn btn-default btn-lg" asp-controller="Management" asp-action="Index">
                <i class="fas fa-hand-holding-usd"></i>
            </button>

            <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="theMenu" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Management" asp-action="Index"><i class="fas fa-hand-holding-usd"></i>Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Management" asp-action="About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Employees" asp-action="Index">Employees</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Benefits" asp-action="Index">Benefits</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Management" asp-action="Contact">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <section class="container">
        <div class="col-md-12">
            <h2 class="text-center">@ViewBag.Title</h2>
            @RenderBody()
        </div>
    </section>
    <footer class="container">
        <div class="text-center">Copyright 2020 Marvelo LLC</div>
    </footer>

    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/js/index.js"></script>*@
    @RenderSection("scripts", false)
</body>
</html>